import './globals.css'

export const metadata = {
  title: 'final-timestamp-test-20251019-052237',
  description: 'Generated by Neuronix',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}